### ISSUE TITLE
能不能提供一些启动配置的修改

### ISSUE THREAD

**Issue by ChitaGideon** [LeoHaoVIP/AListLiteAndroid#1]
比如ssl key
数据库连接配置

**Comment by LeoHaoVIP** [comment]
【低优先级】feature 已记录，等待排期

**Comment by LeoHaoVIP** [comment]
AListLite 目前已支持用户手动修改 AList 配置文件，配置修改入口为版本信息页面下方的 `高级配置`。
[功能介绍](https://github.com/LeoHaoVIP/AListLiteAndroid?tab=readme-ov-file#advanced)
