### ISSUE TITLE
alistlib.aar包损坏，请帮忙更新。

### ISSUE THREAD

**Issue by formatwea** [LeoHaoVIP/AListLiteAndroid#10]
下载最新代码，只有604KB，可能是app/libs/alistlib.aar包损坏，帮忙更新下最新代码。

**Comment by LeoHaoVIP** [comment]
本仓库的 LFS 用量已超额，暂时无法通过仓库提供下载，可转至 Release 页面下载 [alistlib.aar](https://github.com/LeoHaoVIP/AListLiteAndroid/releases/download/v1.1.0-beta1/alistlib.aar)

**Comment by formatwea** [comment]
多谢。
