### ISSUE TITLE
无法挂载115网盘

### ISSUE THREAD

**Issue by lancerwhite** [LeoHaoVIP/AListLiteAndroid#11]
首页出现failed get objs: failed to list objs, invalid characters 'a' looking for beginning of value的提示

**Comment by ttttC9** [comment]
一样的问题

**Comment by LeoHaoVIP** [comment]
新版本已修复，请通过APP更新至最新版本（v1.1.0-beta1）

**Comment by lancerwhite** [comment]
好的，谢谢
