### ISSUE TITLE
挂在哪里好一点？

### ISSUE THREAD

**Issue by ttttC9** [LeoHaoVIP/AListLiteAndroid#13]
Alist挂在自己手机上用Filmly看着还行，挂在自己买的阿里云服务器上就卡了，是因为带宽太小的原因吗？

**Comment by LeoHaoVIP** [comment]
这个不太确定，要看你那边挂的是什么盘，挂载的时候注意不要选择本地代理，否则流量将从服务器端转发

**Comment by ttttC9** [comment]
现在挂在了一个带宽1Gb的服务器上，观看体验还行，挺不错的
