### ISSUE TITLE
9月15日，115突然用不了

### ISSUE THREAD

**Issue by david-cgw** [LeoHaoVIP/AListLiteAndroid#14]
出现failed get objs: failed to list objs: invalid character 'a' looking for beginning of value

alist官方版很快已在3.73版修复这问题，115已经可用了。
请在alistlite.apk也随之更新一下

**Comment by david-cgw** [comment]
请参考原版alist的issue #7216

**Comment by LeoHaoVIP** [comment]
最新版本已解决，请更新至最新版本后查看
