### ISSUE TITLE
期望增加保活机制（TV端）

### ISSUE THREAD

**Issue by xiaoan0120** [LeoHaoVIP/AListLiteAndroid#15]
比较偷懒的想要alist直接安装在安卓TV，然后随便是nova或者其他播放器webdav挂在观看影视
但是观看中，alist进程被杀死就无法继续观看

**Comment by LeoHaoVIP** [comment]
目前 APP 已具备开机自启和后台保活的功能，需要将其电源优化策略设置为无限制，同时在设置中为 APP 开启自启动开关。
