### ISSUE TITLE
potplay 播放地址缺少 ":"，导致无法播放

### ISSUE THREAD

**Issue by Carterzackary** [LeoHaoVIP/AListLiteAndroid#16]
<img width="707" alt="1" src="https://github.com/user-attachments/assets/de8f3fa0-7215-41e1-af2c-5ba59e9df5de">
<img width="338" alt="2" src="https://github.com/user-attachments/assets/c0bd48b1-3f60-46d7-96ed-4eecc633e5fd">

**Comment by Carterzackary** [comment]
<img width="707" alt="1" src="https://github.com/user-attachments/assets/de8f3fa0-7215-41e1-af2c-5ba59e9df5de">
<img width="338" alt="2" src="https://github.com/user-attachments/assets/c0bd48b1-3f60-46d7-96ed-4eecc633e5fd">

**Comment by LeoHaoVIP** [comment]
![image](https://github.com/user-attachments/assets/22fdf8b9-00c5-425c-a717-94d732ae37ec)
未复现
