### ISSUE TITLE
装在机顶盒里，按home键没反应，按遥控器返回显示“机顶盒正在启动”回不到桌面。

### ISSUE THREAD

**Issue by centicenti** [LeoHaoVIP/AListLiteAndroid#17]
装在机顶盒里，按home键没反应，按遥控器返回显示“机顶盒正在启动”回不到桌面。
![image](https://github.com/user-attachments/assets/89182d55-245d-4cb7-a8a1-e41fa6cd2039)

**Comment by centicenti** [comment]
![image](https://github.com/user-attachments/assets/fecc0240-5588-4201-8e31-38fa3978befa)

**Comment by centicenti** [comment]
现在只能通过PC远程发命令过去启动桌面：
![image](https://github.com/user-attachments/assets/a4ce1e1b-140f-4034-a2f2-e573f53615a0)

**Comment by LeoHaoVIP** [comment]
经排查，该问题可能是由于 APP 的返回逻辑导致的，新版本尝试对该问题进行了修复，请更新至最新版本
