### ISSUE TITLE
Alist无法挂载Pikpak

### ISSUE THREAD

**Issue by Andreerassel** [LeoHaoVIP/AListLiteAndroid#19]
在Alist lite 1.1.0 beta4版本中，如下图所示，挂载pikpak会出现如下报错：Failed init storage: oauth2: "invalid_ grant" "refreshoszxxxxxxxxxxxxx"has been refresh at 2024-11-20T18:44:24+08:00" 请修复
![1d53c171256d2dc4cbd99849cd151651_720](https://github.com/user-attachments/assets/2ef51fac-87c6-48e9-9cac-b96d54f71900)

**Comment by Andreerassel** [comment]
![image](https://github.com/user-attachments/assets/e202547d-8207-4976-af88-47ae3276fd7f)
使用的方法shi'zhe'g是这个

**Comment by LeoHaoVIP** [comment]
AList 官方（v3.40.0）尝试对该问题进行了修复，新版本（v1.1.1-beta2）基于该版本构建，请更新至最新版查看。
