### ISSUE TITLE
适配深色模式，支持全屏及支持保持登陆状态

### ISSUE THREAD

**Issue by Plout-hu** [LeoHaoVIP/AListLiteAndroid#2]
1、希望作者能够支持将整个页面适配深色模式（即上方区域能够与下方页面同步变为黑色）
![Screenshot_2024-03-05-09-58-34-108_com leohao android alistlite](https://github.com/LeoHaoVIP/AListLiteAndroid/assets/96678139/c8dd11a6-8806-4643-827b-c77fe3cbbf37)
2、希望能够在播放视频是支持视频全屏播放
![Screenshot_2024-03-05-09-58-56-665_com leohao android alistlite](https://github.com/LeoHaoVIP/AListLiteAndroid/assets/96678139/5051ceac-0363-46bd-a02a-791bf33200c2)
3、软件存在登陆状态丢失的问题，经常需要重新输入密码才能进入后台
4、首次加载异常，当杀掉软件后台后进入软件需要手动刷新才能正常显示
![Screenshot_2024-03-05-10-04-49-230_com leohao android alistlite](https://github.com/LeoHaoVIP/AListLiteAndroid/assets/96678139/dd4eda14-2362-40be-baba-c300a7d3e31d)

**Comment by LeoHaoVIP** [comment]
1. 深色模式暂不在开发计划中
2. 新版本（v1.0.9-beta3） 已支持视频全屏播放
3. 新版本已修复登录状态丢失的问题
4. AList 启动时会加载挂载的存储列表，需要一定的时间，本项目无法修改，不列入开发计划
