### ISSUE TITLE
115 网盘下载链接错误

### ISSUE THREAD

**Issue by CEX68** [LeoHaoVIP/AListLiteAndroid#25]
1. 进入挂载的 115 网盘
2. 选中文件
3. 点击下载图标，不能下载，显示“已永久移动到新的网址”
4. 选中文件后，复制下载链接，能正常下载。其他网盘没发现这个问题

AListLiteAndroid 版本 v3.40.0

**Comment by LeoHaoVIP** [comment]
该问题已在 AList v3.41.0 修复，预计本周会同步发布一版

**Comment by jinhongrui5844** [comment]
我老是掉线，咋办？是不是需要更新版本，为了找你都跑这里来了

**Comment by LeoHaoVIP** [comment]
> 我老是掉线，咋办？是不是需要更新版本，为了找你都跑这里来了

请下载新版本再做尝试
