### ISSUE TITLE
这个有没有webdav功能？

### ISSUE THREAD

**Issue by jacketchain** [LeoHaoVIP/AListLiteAndroid#26]
我想在手机上安装这个软件，然后再通过webdav功能连接到网易爆米花里，可是试了好几次都不行，不知道啥原因。

**Comment by LeoHaoVIP** [comment]
支持的，检查下 dav 路径是否有误哈
https://alist.nn.ci/zh/guide/webdav.html#webdav-%E5%AD%98%E5%82%A8%E6%94%AF%E6%8C%81

**Comment by jacketchain** [comment]
![Screenshot_20241224_003350_com.oumi.utility.media.hub.jpg](https://github.com/user-attachments/assets/a1805302-ee97-4d8d-be81-a1c0f76d3013)

这个设置感觉没问题，但是链接不成功，偶尔能连上又获取不到文件信息
