### ISSUE TITLE
 zip END header not found

### ISSUE THREAD

**Issue by HD-L** [LeoHaoVIP/AListLiteAndroid#3]
Execution failed for AarToClassTransform: /Users/****/grable/caches/transforms-3/43bcc0216efdb14390a46a8c666088c7/transformed/jetified-alistlib.aar.
         > zip END header not found
         
         无法编译
         
<img width="508" alt="image" src="https://github.com/LeoHaoVIP/AListLiteAndroid/assets/18065322/16c0dad5-1846-410c-b7a1-9bc879e92f42">
java11
mac系统

**Comment by LeoHaoVIP** [comment]
猜测是 arr 包已损坏，请尝试重新 clone 项目或更新 gradle 构建工具
