### ISSUE TITLE
能否支持投屏

### ISSUE THREAD

**Issue by ppllpig** [LeoHaoVIP/AListLiteAndroid#5]
调用局域网pot，不登录网页，手机端操作

**Comment by LeoHaoVIP** [comment]
浏览器本身不支持投屏操作，故没有该开发计划。

P.S. 下一个版本将修复无法调用本地应用播放视频的问题，届时你可以通过第三方播放器实现投屏到其他设备（或使用支持 WebDAV 协议的播放器直接挂载播放）
